### ISSUE TITLE
User account management APIs

### ISSUE THREAD

**Issue by ggvelev** [ggvelev/smart-home#11]
# Overview
Expose REST APIs for user account registration, update, delete/deactivate.
# Tasks
- [x] User registration
- [ ] User registration confirmation
- [ ] User account details update
- [x] User account delete/deactivate
