### ISSUE TITLE
Setup core MQTT listeners & publishers

### ISSUE THREAD

**Issue by ggvelev** [ggvelev/smart-home#13]
# Overview

Define listeners and publishers for core MQTT topics which the application uses to communicate with devices. Such topics are:
- `devices/{deviceId}/commands`
- `devices/{deviceId}/config`
- `devices/{deviceId}/commands/{commandId}`
- `devices/{deviceId}/state`

# Tasks
- [x] Define publisher for device commands @ `devices/{deviceId}/commands`
- [ ] Define listener for status of commands executed by device (approach is subject to changes in design) @ `devices/{deviceId}/commands/{commandId}`
- [ ] #17
- [x] Define listener for device state change (i.e. environmental sensor readings/measurements) @ `devices/{deviceId}/state`
