### ISSUE TITLE
Persistence layer

### ISSUE THREAD

**Issue by ggvelev** [ggvelev/smart-home#2]
# Overview:
Define database schema and back-end entities
# Tasks:
- [x] RDBMS schema and relations
- [x] JPA entities and repositories
- [x] InfluxDB time-series persistence
