### ISSUE TITLE
IoT devices firmware

### ISSUE THREAD

**Issue by ggvelev** [ggvelev/smart-home#4]
# Overview:
Design and implement basic firmware for embedded devices that will communicate with the *smart-home* application server.
Arduino IDE and libraries will be used.
# Tasks:
- [x] Define appropriate library to use for all devices that will talk with the server
- [x] Setup Wi-Fi connectivity
- [x] Setup MQTT client
- [ ] HTTP APIs for management/configuration of devices
