### ISSUE TITLE
Web UI implementation

### ISSUE THREAD

**Issue by ggvelev** [ggvelev/smart-home#5]
# Overview:
Implement a simple client web application (front-end) that will consume the exposed REST APIs.
To be implemented with HTML, CSS, JS, jQuery, ChartJS.
# Tasks:
- [x] User registration, login and logout
- [ ] User account management
- [x] Device management
- [x] Sensor data visualization (time-series charts)
- [x] Event notifications configuration
