### ISSUE TITLE
Security, authentication and authorization

### ISSUE THREAD

**Issue by ggvelev** [ggvelev/smart-home#8]
# Overview:
Apply some basic security configuration.
# Tasks:
- [ ] Apply HTTPS (TLS)
- [x] Authentication via username and password credentials
- [x] Authentication via JSON Web Tokens (JWT)
- [ ] Define authorization rules, RBAC
