### ISSUE TITLE
Device management operations and public REST APIs

### ISSUE THREAD

**Issue by ggvelev** [ggvelev/smart-home#9]
# Overview:
Implementation of core features related to device management and operations.
# Tasks:
- [x] Expose REST APIs for device data management CRUD operations
- [x] Expose REST APIs for device properties management CRUD operations
- [ ] #18
- [x] REST APIs for retrieval/deletion of device state records
- [x] REST APIs for initiating command execution and status tracking (might change or drop)
